webview/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views
from django.views.static import serve

from webview import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('lista.urls')),
]
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?:.*)$', serve, {'document_root': settings.STATIC_ROOT, })
]

lista/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Author(models.Model):
    authorid = models.AutoField(db_column='authorId', primary_key=True)  # Field name made lowercase.
    name = models.CharField(max_length=100, blank=True, null=True)
    image = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'authors'


class Difficulty(models.Model):
    difficultid = models.PositiveIntegerField(db_column='difficultId', primary_key=True)  # Field name made lowercase.
    name = models.TextField()

    class Meta:
        managed = False
        db_table = 'difficulties'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Historic(models.Model):
    id = models.AutoField(primary_key=True)
    userid = models.IntegerField(db_column='userId')  # Field name made lowercase.
    username = models.CharField(db_column='userName', max_length=100)  # Field name made lowercase.
    itemid = models.IntegerField(db_column='itemId')  # Field name made lowercase.
    itemname = models.TextField(db_column='itemName')  # Field name made lowercase.
    operationid = models.SmallIntegerField(db_column='operationId', db_comment='1->create, 2->update, 3->check, 4->uncheck, 5->delete')  # Field name made lowercase.
    createdat = models.DateTimeField(db_column='createdAt', blank=True, null=True)  # Field name made lowercase.
    firebasesent = models.IntegerField(db_column='firebaseSent', blank=True, null=True)  # Field name made lowercase.
    remoteaddr = models.CharField(db_column='remoteAddr', max_length=45, blank=True, null=True)  # Field name made lowercase.
    originaldata = models.TextField(db_column='originalData', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'historic'


class Image(models.Model):
    imageid = models.AutoField(db_column='imageId', primary_key=True)  # Field name made lowercase.
    recipeid = models.ForeignKey('Recipe', models.CASCADE, db_column='recipeId')  # Field name made lowercase.
    name = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'images'


class Ingredient(models.Model):
    ingredientid = models.AutoField(db_column='ingredientId', primary_key=True)  # Field name made lowercase.
    name = models.TextField(db_collation='utf8mb4_general_ci', blank=True, null=True)
    isproduct = models.TextField(db_column='isProduct', blank=True, null=True)  # Field name made lowercase. This field type is a guess.
    ischecked = models.CharField(db_column='isChecked', max_length=1, blank=True, null=True)  # Field name made lowercase.
    quantity = models.IntegerField(blank=True, null=True)
    comment = models.TextField(db_collation='utf8mb4_general_ci', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ingredients'
        ordering = ['ischecked', 'name']

class Log(models.Model):
    message = models.CharField(max_length=200, primary_key=True)
    datetime = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'log'


class Mealingredient(models.Model):
    mealid = models.OneToOneField('Meal', models.CASCADE, db_column='mealId', primary_key=True)  # Field name made lowercase. The composite primary key (mealId, ingredientId) found, that is not supported. The first column is selected.
    ingredientid = models.ForeignKey(Ingredient, models.CASCADE, db_column='ingredientId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'mealingredients'
        unique_together = (('mealid', 'ingredientid'),)


class Meal(models.Model):
    mealid = models.AutoField(db_column='mealId', primary_key=True)  # Field name made lowercase.
    name = models.TextField(db_collation='utf8mb4_general_ci', blank=True, null=True)
    islunch = models.IntegerField(db_column='isLunch')  # Field name made lowercase.
    ischecked = models.IntegerField(db_column='isChecked')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'meals'


class Note(models.Model):
    noteid = models.AutoField(db_column='noteId', primary_key=True)  # Field name made lowercase.
    recipeid = models.ForeignKey('Recipe', models.CASCADE, db_column='recipeId')  # Field name made lowercase.
    note = models.CharField(max_length=500)

    class Meta:
        managed = False
        db_table = 'notes'


class Operation(models.Model):
    operationid = models.IntegerField(db_column='operationId', primary_key=True)  # Field name made lowercase.
    authorid = models.IntegerField(db_column='authorId', blank=True, null=True)  # Field name made lowercase.
    productid = models.IntegerField(db_column='productId', blank=True, null=True)  # Field name made lowercase.
    typeid = models.IntegerField(db_column='typeId', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'operations'


class Otherchild(models.Model):
    id = models.AutoField(primary_key=True)
    parentid = models.ForeignKey('Otherparent', models.CASCADE, db_column='parentId')  # Field name made lowercase.
    name = models.CharField(max_length=100)
    ischecked = models.IntegerField(db_column='isChecked')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'otherschild'


class Otherparent(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'othersparent'


class Recipeingredient(models.Model):
    ingredientid = models.OneToOneField(Ingredient, models.CASCADE, db_column='ingredientId', primary_key=True)  # Field name made lowercase. The composite primary key (ingredientId, recipeId) found, that is not supported. The first column is selected.
    recipeid = models.ForeignKey('Recipe', models.CASCADE, db_column='recipeId')  # Field name made lowercase.
    number = models.CharField(max_length=50, db_collation='latin1_swedish_ci', blank=True, null=True)

lista/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .forms import *
from .models import Ingredient

@login_required
def ingredient_list(request):
    form = FilterIngredientForm(request.GET or None)
    check_form = CheckIngredientForm(request.POST)
    ingredients = Ingredient.objects.all()

    if form.is_valid():
        search = form.cleaned_data.get('search')
        if search:
            ingredients = ingredients.filter(Q(name__icontains=search) | Q(comment__icontains=search))

    return render(
        request, 
        'ingredient/ingredient_list.html', 
        {
            'ingredients': ingredients, 
            'form': form, 
            'checkform': check_form
        })

@login_required
def ingredient_new(request):
    if request.method == 'POST':
        form = IngredientForm(request.POST)

        if form.is_valid():
            ingredient = form.save()
            ingredient.save()
            return redirect('ingredient_list')
    else:
        form = IngredientForm(request.POST)

    return render(request, 'ingredient/ingredient_edit.html', {'form': form})

@login_required
def ingredient_edit(request, pk):
    item = get_object_or_404(Ingredient, pk=pk)
    if request.method == 'POST':
        form = IngredientForm(request.POST, instance=item)
        if form.is_valid():
            item.isproduct = '\x01'
            item = form.save()
            return redirect('ingredient_list')
    else:
        form = IngredientForm(instance=item)

    return render(request, 'ingredient/ingredient_edit.html', {'form': form})

@login_required
def ingredient_check(request, pk):
    item = get_object_or_404(Ingredient, pk=pk)
    if request.method == 'POST':
        form = CheckIngredientForm(request.POST, instance=item)
        if form.is_valid():
            item.isproduct = '\x01'
            item.ischecked = '0' if item.ischecked == '0' else '1'
            item = form.save()
    else: 
        form = CheckIngredientForm(instance=item)

    return redirect('ingredient_list')

@login_required
def ingredient_increase(request, pk):
    return ingredient_modify_quantity(request, pk, True)

@login_required
def ingredient_decrease(request, pk):
    return ingredient_modify_quantity(request, pk, False)

def ingredient_modify_quantity(request, pk, increase):
    item = get_object_or_404(Ingredient, pk=pk)
    if request.method == 'POST':
        form = QuantityIngredientForm(request.POST, instance=item)
        if form.is_valid():
            item.isproduct = '\x01'
            increment = 1 if increase else - 1
            item.quantity += increment 
            if item.quantity == 0: item.quantity = 1
            item = form.save()
    else: 
        form = QuantityIngredientForm(instance=item)

    return redirect('ingredient_list')

@login_required
def ingredient_delete(request, pk):
    item = get_object_or_404(Ingredient, pk=pk)
    item.delete()

    return redirect('ingredient_list')

lista/views/ingredient_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from ..forms.ingredient_forms import *
from ..models import Ingredient

@login_required
def ingredient_list(request):
    form = FilterIngredientForm(request.GET or None)
    check_form = CheckIngredientForm(request.POST)
    ingredients = Ingredient.objects.all()

    if form.is_valid():
        search = form.cleaned_data.get('search')
        if search:
            ingredients = (ingredients
                           .filter(Q(name__icontains=search) | Q(comment__icontains=search))
                           .order_by('name'))

    return render(
        request, 
        'ingredient/ingredient_list.html', 
        {
            'ingredients': ingredients, 
            'form': form, 
            'checkform': check_form
        })

@login_required
def ingredient_new(request):
    if request.method == 'POST':
        form = IngredientForm(request.POST)

        if form.is_valid():
            ingredient = form.save()
            ingredient.save()
            return redirect('ingredient_list')
    else:
        form = IngredientForm(request.POST)

    return render(request, 'ingredient/ingredient_edit.html', {'form': form})

@login_required
def ingredient_edit(request, pk):
    item = get_object_or_404(Ingredient, pk=pk)
    if request.method == 'POST':
        form = IngredientForm(request.POST, instance=item)
        if form.is_valid():
            item.isproduct = '\x01'
            item = form.save()
            return redirect('ingredient_list')
    else:
        form = IngredientForm(instance=item)

    return render(request, 'ingredient/ingredient_edit.html', {'form': form})

@login_required
def ingredient_check(request, pk):
    item = get_object_or_404(Ingredient, pk=pk)
    if request.method == 'POST':
        form = CheckIngredientForm(request.POST, instance=item)
        if form.is_valid():
            item.isproduct = '\x01'
            item.ischecked = '0' if item.ischecked == '0' else '1'
            item = form.save()
    else: 
        form = CheckIngredientForm(instance=item)

    return redirect('ingredient_list')

@login_required
def ingredient_increase(request, pk):
    return ingredient_modify_quantity(request, pk, True)

@login_required
def ingredient_decrease(request, pk):
    return ingredient_modify_quantity(request, pk, False)

def ingredient_modify_quantity(request, pk, increase):
    item = get_object_or_404(Ingredient, pk=pk)
    if request.method == 'POST':
        form = QuantityIngredientForm(request.POST, instance=item)
        if form.is_valid():
            item.isproduct = '\x01'
            increment = 1 if increase else - 1
            item.quantity += increment 
            if item.quantity == 0: item.quantity = 1
            item = form.save()
    else: 
        form = QuantityIngredientForm(instance=item)

    return redirect('ingredient_list')

@login_required
def ingredient_delete(_, pk):
    item = get_object_or_404(Ingredient, pk=pk)
    item.delete()

    return redirect('ingredient_list')

lista/templates/meal/meal_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="form-signin w-50 p-3 m-auto" style="min-width:300px">
    <h2>{% if form.name.value %} Editar {% else %} Nuevo {% endif %} ítem</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label_tag }}</label>
            <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.html_name }}" value="{% if form.name.value %} {{form.name.value}} {% endif %}">
            <div class="text-danger">{{ form.name.errors }}</div>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="{{ form.ischecked.id_for_label }}" name="{{ form.ischecked.html_name }}" {% if form.initial.ischecked == 1 %} checked {% endif %}>
            <label for="{{ form.ischecked.id_for_label }}" class="form-check-label">{{ form.ischecked.label_tag }}</label>
            <div class="text-danger">{{ form.ischecked.errors }}</div>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="{{ form.islunch.id_for_label }}" name="{{ form.islunch.html_name }}" {% if form.initial.islunch == 1 %} checked {% endif %}>
            <label for="{{ form.islunch.id_for_label }}" class="form-check-label">{{ form.islunch.label_tag }}</label>
            <div class="text-danger">{{ form.islunch.errors }}</div>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="{% url 'meal_list' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

{% endblock %}

lista/templates/meal/meal_list.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-body">
        <div class="row g-3">
            <div class="col-8">
                <form method="GET" name="searchForm">
                    {% csrf_token %}
                    <label for="{{ form.search.id_for_label }}" class="form-label">{{ form.search.label_tag }}</label>
                    <input type="text" class="form-control" id="{{ form.search.id_for_label }}" name="{{ form.search.html_name }}"
                    placeholder="Enter para buscar">
                    {{ form.search.errors }}
                </form>
            </div>
            <div class="col-2 d-flex justify-content-end">
                <input type="reset" class="btn btn-secondary align-self-end" onclick="document.searchForm.submit()"> 
            </div>
            <div class="col-2 d-flex justify-content-end">
                <a class="btn btn-primary align-self-end" href="{% url 'meal_new' %}">Añadir nuevo</a>
            </div>
        </div>
    </div>
</div>
<div class="card my-3 fit-height overflow-auto">
    <div class="card-body">
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <table class="table table-hover table-bordered">
                            <thead>
                                <tr class="table-secondary">
                                    <th scope="col">Almuerzos</th>
                                    <th scope="col" class="fit-3-icons">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for lunch in lunches %}
                                <tr>
                                    <td onclick="this.firstElementChild.submit()" role="button">
                                        <form method="POST" action="{% url 'meal_check' pk=lunch.pk %}" class="column-fit d-inline">
                                            {% csrf_token %}
                                            <input type="checkbox" name="ischecked" onclick="this.form.submit()"
                                                class="form-check-input" id="id_ischecked" {% if meal.ischecked == 1 %} checked {% endif %}>
                                        </form>
                                        {{ lunch.name }}
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal"
                                            data-bs-target="#globalModal" data-bs-name="{{ lunch.name }}"
                                            data-bs-function="meal" data-bs-id="{{ lunch.pk }}" data-bs-operation="ingredients">
                                            <i class="fa-solid fa-drumstick-bite"></i>
                                        </button>
                                        <a href="{% url 'meal_edit' pk=lunch.pk %}" class="btn btn-warning btn-sm">
                                            <i class="fa-solid fa-pen-to-square"></i>
                                        </a>
                                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal"
                                            data-bs-target="#globalModal" data-bs-name="{{ lunch.name }}"
                                            data-bs-function="meal" data-bs-id="{{ lunch.pk }}" data-bs-operation="delete">
                                            <i class="fa-solid fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <table class="table table-hover table-bordered">
                            <thead>
                                <tr class="table-secondary">
                                    <th scope="col">Cenas</th>
                                    <th scope="col" class="fit-3-icons">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for dinner in dinners %}
                                <tr>
                                    <td onclick="this.firstElementChild.submit()" role="button">
                                        <form method="POST" action="{% url 'meal_check' pk=dinner.pk %}" class="column-fit d-inline">
                                            {% csrf_token %}
                                            <input type="checkbox" name="ischecked" onclick="this.form.submit()"
                                                class="form-check-input" id="id_ischecked" {% if meal.ischecked == 1 %} checked {% endif %}>
                                        </form>
                                        {{ dinner.name }}
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal"
                                            data-bs-target="#globalModal" data-bs-name="{{ dinner.name }}"
                                            data-bs-function="meal" data-bs-id="{{ dinner.pk }}" data-bs-operation="ingredients">
                                            <i class="fa-solid fa-drumstick-bite"></i>
                                        </button>
                                        <a href="{% url 'meal_edit' pk=dinner.pk %}" class="btn btn-warning btn-sm">
                                            <i class="fa-solid fa-pen-to-square"></i>
                                        </a>
                                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal"
                                            data-bs-target="#globalModal" data-bs-name="{{ dinner.name }}" data-bs-operation="delete"
                                            data-bs-function="meal" data-bs-id="{{ dinner.pk }}">
                                            <i class="fa-solid fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="row">
                    <div class="col">
                        <table class="table table-hover table-bordered">
                            <thead>
                                <tr class="table-secondary">
                                    <th scope="col">Posibles comidas</th>
                                    <th scope="col" class="fit-4-icons">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for possible_meal in possible_meals %}
                                <tr>
                                    <td>{{ possible_meal.name }}</td>
                                    <td>
                                        <a href="{% url 'meal_edit' pk=possible_meal.pk %}" class="btn btn-warning btn-sm">
                                            <i class="fa-solid fa-pen-to-square"></i>
                                        </a>
                                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal"
                                            data-bs-target="#globalModal" data-bs-name="{{ possible_meal.name }}"
                                            data-bs-function="meal" data-bs-id="{{ possible_meal.pk }}" data-bs-operation="delete">
                                            <i class="fa-solid fa-trash"></i>
                                        </button>
                                        <form method="POST" action="{% url 'meal_choose' pk=possible_meal.pk %}" class="column-fit d-inline">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-success btn-sm">
                                                <i class="fa-solid fa-sun"></i>
                                            </button>
                                        </form>
                                        <form method="POST" action="{% url 'meal_choose_dinner' pk=possible_meal.pk %}" class="column-fit d-inline">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-info btn-sm">
                                                <i class="fa-solid fa-moon"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="hidden_ingredient_list" class="d-none">
    <div>
        <table class="table table-hover table-bordered">
            <thead >
                <tr class="table-secondary">
                    <th scope="col">Ingredientes</th>
                </tr>
            </thead>
            <tbody>
                {% for ingredient in ingredients %}
                <tr>
                    <td>
                        <div class="form-check" onclick="checkIngredient(this)" role="button">
                            <input type="checkbox"
                                class="form-check-input ingredient-list" id="check-{{ ingredient.pk }}" name="check-{{ ingredient.pk }}">
                            <label class="form-check-label">{{ ingredient.name }}</label>
                            <span class="opacity-50">{% if ingredient.comment %} {{ingredient.comment}} {% endif%}</span>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}